### ISSUE TITLE
Not able to see position of sUAS on ATAK device

### ISSUE THREAD

**Issue by RohanKurane** [sofwerx/push-cursor-on-target#2]
Hi,

I am doing the following - 
build a CoT message
  ` <?xml version="1.0" encoding="UTF-8" standalone="y"?><event how="m-g" type="a-f-A-M-F-Q" uid="A.101" time="2019-01-20T08:13:25:00Z" start="2019-01-20T08:13:30.00Z" stale="2019-01-20T08:16:30:00Z" version="2.0"><detail><contact callsign="My-Drone"/></detail><point lat="37.564" lon="-122.321" hae="43.34" ce="1" le="1"/></event> `

I then send this to a ATAK server which I do a UDP connection to. The send is successful. 

But on my ATAK device (android tablet), I do not see a position. On the TAK app on the tablet I am connected to the server. So my assumption is that once the CoT message is sent to the TAK server, it would send it to all the TAK devices that are connected to it via the TAK app.

Is there anything wrong with the syntax of the message ? Or is there anything else I might bemissing on the app side ?

**Comment by ianblenke** [comment]
Our use case was to send directly to the ATAK app on an android device. From there, my understanding is that it would trickle back upstream to the TAK server and any other ATAK apps that are talking to that server. 

That being said, you would think that sending to the TAK server would work as well.  We did not try this in our deployment, so we can't speak to that.

**Comment by RohanKurane** [comment]
@ianblenke Thanks. 
Can you send me an example of a CoT message that you send to the ATAK app on your android device ? Preferably for a sUAS device position co-ordinates so I can compare to what I have above ?

**Comment by ianblenke** [comment]
This example is in the `README.md` file in this repository:
```
<?xml version="1.0" standalone="yes"?>
<event
	version="2.0"
	uid="J-01334"
	type="a-h-G"
	time="2017-10-30T11:43:38.07Z"
	start="2017-10-30T11:43:38.07Z"
	stale="2017-10-30T11:55:38.07Z">
		<detail></detail>
		<point
			lat="30.0090027"
			lon="-85.9578735"
			hae="1"
			ce="1"
			le="1"/>
</event>
```
Is this what you're looking for?

**Comment by ianblenke** [comment]
This might help as well:

https://www.mitre.org/publications/technical-papers/cursorontarget-message-router-users-guide

**Comment by RohanKurane** [comment]
@ianblenke
Thanks. Yes I did look at the example and the doc. Does my example what I posted look correct to you? 
I assume there are no new line characters at the end of each line and just one at the very end. Is that right ? 
Perhaps there is something on the TAK server that is dropping my message and not sending it to the TAK device?

**Comment by ianblenke** [comment]
Sounds likely. Have you tried sending it to an ATAK device like we did?

**Comment by RohanKurane** [comment]
@ianblenke 
I wouldnt know how to do that. 
Are you sending CoT messages straight from your application to the device ? Is your device also acting as a TAK server or is your application running on a TAK server ?
My application runs on an independent server and the TAK server and TAK devices are 2 separate entities.

**Comment by RohanKurane** [comment]
@ianblenke
Wanted to let you know that I got it to work. Thanks for your help btw.

**Comment by nsimoncini** [comment]
Where do you get the TAK Server?

**Comment by RohanKurane** [comment]
I have (or had) a test server I was working with.

**Comment by nsimoncini** [comment]
Any idea on where to get a copy?

**Comment by RohanKurane** [comment]
Im not sure if its still available. I will check and get back to you (It was a private installation I was working with so I need to check)

**Comment by nsimoncini** [comment]
Appreciate it.

**Comment by RohanKurane** [comment]
What is your use case if you don't mind me asking ?

**Comment by nsimoncini** [comment]
Public Safety / First Responders.

**Comment by rznazn** [comment]
@ianblenke, Hi, I'm trying to send cot directly to an ATAK device, and nothing is showing up. I've tried a few different COT examples i copy/pasted in and a few different of the default input ips and ports on atak. and I'm still getting nothing. Which IP:port combo on atak were you sending too?

**Comment by splashd1** [comment]
If I forward COT from another system to a TAK server, will it proliferate to ATAK devices? wouldn't this be preferable to sending to individual devices. One of my concerns is ATAK using mobile IP, and not always knowing my destination address. Maybe I'm missing something, but I have a system that needs to share positions with ATAK, and I'd like feedback. To me, it makes more sense to talk to the TAK server. Thanks

**Comment by ianblenke** [comment]
Seems logical to me. Unfortunately, I've long since moved on, and I no longer have access to a TAK server to help figure that out. Even though I did have access to a TAK server at the time, once we figured out how to send the COT XML directly to the tcp port on the Android device we really didn't pursue it.
